# Generated by Django 4.1.4 on 2023-06-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiencia",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Realizada", "Realizada"),
                    ("Cancelada", "Cancelada"),
                    ("Remarcada", "Remarcada"),
                ],
                default="Pendente",
                max_length=15,
                verbose_name="Situação da audiência",
            ),
        ),
    ]
