# Generated by Django 4.1.4 on 2023-06-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_audiencia_situacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiencia",
            name="data_do_processo_antiga",
            field=models.DateTimeField(
                null=True, verbose_name="Data e horário da audiência antiga"
            ),
        ),
    ]
